name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn@1.22.17
      - name: Gradle Version
        run: ./gradlew --version
      - name: Build
        run: ./gradlew build -PtestAllSupportedGradleVersions=true -PtestProxyIntegrationTests=false
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Gradle Version
        run: ./gradlew --version
      - name: Build
        run: ./gradlew build -PtestProxyIntegrationTests=false
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Gradle Version
        run: ./gradlew --version
      - name: Build
        run: ./gradlew build -PtestProxyIntegrationTests=false
